### ISSUE TITLE
npm package nema does not exist

### ISSUE THREAD

**Issue by jadonk** [BeagleBoneCookbook/firstEdition#2]

**Comment by jadonk** [comment]
Here's an alternate demo, but currently only tested on Blue with EM-506: https://gist.github.com/jadonk/7169ce12a91f08a48dac901b7c62ec3b

**Comment by jadonk** [comment]
Pointer to the issue: https://github.com/BeagleBoneCookbook/firstEdition/blob/master/02sensors/GPS.js#L2

**Comment by MarkAYoder** [comment]
The package is nmea.  It looks like it's still on npm.

--Mark
